# Header

menu:
  主页: /
  面经: /categories/面经//
  Cpp: /categories/Cpp//
  Leetcode学习笔记: /categories/Leetcode//
  操作系统: /categories/计算机基础//
  计算机网络: /categories/计算机网络//
  数据库: /categories/数据库//
  深度学习: /categories/DeepLearning//
  我的项目: /categories/myprj//
  Tech issues: /categories/techissue//
  


# SubNav
subnav:
  github: "https://github.com/DDDDDaryl"
  #weibo: "#"
  #rss: "#"
  #zhihu: "#"
  #qq: "#"
  #weixin: "#"
  #jianshu: "#"
  #douban: "#"
  #segmentfault: "#"
  #bilibili: "#"
  #acfun: "#"
  #mail: "frankyoung12138@qq.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: /

# Content

# 文章太长，截断按钮文字
excerpt_link: more
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: '展开全文'
# 数学公式
mathjax: true
# 是否在新窗口打开链接
open_in_new: false

# 打赏
# 打赏type设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 0
# 打赏wording
reward_wording: '谢谢你请我吃糖果'
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
alipay: 
# 微信二维码图片地址
weixin: 

# 目录
# 目录设定：0-不显示目录； 1-文章对应的md文件里有toc:true属性，才有目录； 2-所有文章均显示目录
toc: 2
# 根据自己的习惯来设置，如果你的目录标题习惯有标号，置为true即可隐藏hexo重复的序号；否则置为false
toc_hide_index: false
# 目录为空时的提示
toc_empty_wording: 'Oops, a search miss…'

# 是否有快速回到顶部的按钮
top: true

# Miscellaneous
baidu_analytics: 4797b34b3552c7683a9a186567e053ac
google_analytics: UA-167569898-1
favicon: /assets/pics/cabin.png

#你的头像url
avatar: /assets/pics/Avatar.JPG

#是否开启分享
share_jia: true

#评论：1、多说；2、网易云跟帖；3、畅言；4、Disqus；5、Gitment
#不需要使用某项，直接设置值为false，或注释掉
#具体请参考wiki：https://github.com/litten/hexo-theme-yilia/wiki/

#1、多说
duoshuo: false

#2、网易云跟帖
wangyiyun: false

#3、畅言
changyan_appid: false
changyan_conf: false

#4、Disqus 在hexo根目录的config里也有disqus_shortname字段，优先使用yilia的
disqus: false

#5、Gitment
gitment_owner: false      #你的 GitHub ID
gitment_repo: ''          #存储评论的 repo
gitment_oauth:
  client_id: ''           #client ID
  client_secret: ''       #client secret

#6. Gitalk
gitalk: 
  enable: true    #用来做启用判断可以不用
  clientID: 1484af2d5954c6b6f389    #Github上生成的
  clientSecret: 27c3298fa0f611eb6800f94e58d14bb475575aaa   #同上
  repo: DDDDDaryl.github.io    #评论所在的github project
  owner: DDDDDaryl    #github用户名
  admin: DDDDDaryl    #可以初始化评论issue的github账户名称
  distractionFreeMode: true

# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: '#4d4d4d'
  # 右滑板块背景
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: false

# 智能菜单
# 如不需要，将该对应项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu: 
  innerArchive: '所有文章'
  #friends: '友链'
  aboutme: '关于我'

friends:
  友情链接1: http://localhost:4000/
  友情链接2: http://localhost:4000/
  友情链接3: http://localhost:4000/
  友情链接4: http://localhost:4000/
  友情链接5: http://localhost:4000/
  友情链接6: http://localhost:4000/

aboutme: 华南某工大学自动化小硕^v^<br><br>在此记录一些思考问题的过程<br>把学习当成乐趣吧！